"""
Email sending module — SMTP-based, supports Gmail / Zoho / Microsoft 365 / Custom.

All providers are accessed via STARTTLS SMTP using an App Password.
No OAuth flow is needed; the user generates an App Password from their
provider's security settings and enters it in the Email Setup tab.
"""

import calendar
import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

_TEMPLATE_PATH = Path(__file__).parent.parent / "templates" / "reminder_email.html"


# ── HTML template ─────────────────────────────────────────────────────────────

def _load_template() -> str:
    if _TEMPLATE_PATH.exists():
        return _TEMPLATE_PATH.read_text(encoding="utf-8")
    return _BUILTIN_TEMPLATE


_BUILTIN_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Compliance Reminder</title></head>
<body style="margin:0;padding:0;background:#f4f6f9;font-family:Arial,sans-serif;">
<table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f6f9;padding:30px 0;">
<tr><td align="center">
<table width="680" cellpadding="0" cellspacing="0"
       style="background:#ffffff;border-radius:8px;overflow:hidden;
              box-shadow:0 2px 8px rgba(0,0,0,0.08);">
  <!-- Header -->
  <tr>
    <td style="background:#1a3c5e;padding:28px 32px;">
      <h1 style="margin:0;color:#ffffff;font-size:22px;font-weight:700;">
        Compliance Reminder
      </h1>
      <p style="margin:6px 0 0;color:#a8c4e0;font-size:14px;">
        {month_name} {year} — Action Required
      </p>
    </td>
  </tr>
  <!-- Body -->
  <tr>
    <td style="padding:32px;">
      <p style="margin:0 0 16px;font-size:15px;color:#333;">
        Dear <strong>{client_name}</strong>,
      </p>
      <p style="margin:0 0 20px;font-size:14px;color:#555;line-height:1.6;">
        This is a reminder of your upcoming compliance obligations for
        <strong>{month_name} {year}</strong>. Please ensure timely filing to
        avoid interest, penalties, and late fees.
      </p>
      {compliance_table}
      <p style="margin:24px 0 0;font-size:13px;color:#555;line-height:1.6;">
        Kindly arrange for the necessary documents and information well in advance.
        Please contact our office if you have any questions or require assistance.
      </p>
    </td>
  </tr>
  <!-- Footer -->
  <tr>
    <td style="background:#f8f9fb;padding:20px 32px;border-top:1px solid #eee;">
      <p style="margin:0;font-size:11px;color:#999;line-height:1.6;">
        This is an automated reminder generated by CA Compliance Reminder.<br>
        Personal data processed under the Digital Personal Data Protection Act, 2023 (DPDP Act).<br>
        Data is encrypted at rest and used solely to send this compliance reminder.
      </p>
    </td>
  </tr>
</table>
</td></tr>
</table>
</body>
</html>"""


def _build_compliance_table(compliances: list[dict], month_name: str, year: int) -> str:
    if not compliances:
        return (
            '<p style="color:#888;font-style:italic;">'
            "No specific compliances found for this period.</p>"
        )

    rows_html = ""
    for c in compliances:
        due_day = c.get("custom_due_day") or c.get("due_day")
        due_str = (
            f"{due_day} {month_name} {year}" if due_day else "As applicable"
        )
        rows_html += f"""
    <tr>
      <td style="padding:10px 14px;border-bottom:1px solid #f0f0f0;
                 font-size:13px;color:#333;">{c.get('name', '')}</td>
      <td style="padding:10px 14px;border-bottom:1px solid #f0f0f0;
                 font-size:13px;color:#555;">{c.get('category', '')}</td>
      <td style="padding:10px 14px;border-bottom:1px solid #f0f0f0;
                 font-size:13px;font-weight:600;color:#c0392b;">{due_str}</td>
    </tr>"""

    return f"""
<table width="100%" cellpadding="0" cellspacing="0"
       style="border-collapse:collapse;border:1px solid #e8e8e8;
              border-radius:6px;overflow:hidden;margin:8px 0 16px;">
  <thead>
    <tr style="background:#f0f4f8;">
      <th style="padding:10px 14px;text-align:left;font-size:12px;
                 color:#666;text-transform:uppercase;letter-spacing:.5px;">
        Compliance
      </th>
      <th style="padding:10px 14px;text-align:left;font-size:12px;
                 color:#666;text-transform:uppercase;letter-spacing:.5px;">
        Category
      </th>
      <th style="padding:10px 14px;text-align:left;font-size:12px;
                 color:#666;text-transform:uppercase;letter-spacing:.5px;">
        Due Date
      </th>
    </tr>
  </thead>
  <tbody>{rows_html}
  </tbody>
</table>"""


def _plain_text(client_name: str, compliances: list[dict],
                month_name: str, year: int) -> str:
    lines = [
        f"Dear {client_name},",
        "",
        f"Compliance Reminder — {month_name} {year}",
        "=" * 45,
        "",
    ]
    for c in compliances:
        due_day = c.get("custom_due_day") or c.get("due_day")
        due_str = f"{due_day} {month_name} {year}" if due_day else "As applicable"
        lines.append(f"  • {c['name']} ({c['category']}) — Due: {due_str}")
    lines += [
        "",
        "Please ensure timely compliance to avoid penalties.",
        "Contact our office for any assistance.",
        "",
        "-- CA Compliance Reminder (automated)",
        "Data processed under DPDP Act, 2023.",
    ]
    return "\n".join(lines)


# ── Public API ────────────────────────────────────────────────────────────────

def send_reminder_email(
    account: dict,
    client: dict,
    compliances: list[dict],
    year: int,
    month: int,
    conn: Optional[smtplib.SMTP] = None,
) -> tuple[bool, str]:
    """
    Send one compliance reminder to *client* via *account*.
    Returns (success, error_message).
    """
    month_name = calendar.month_name[month]
    template   = _load_template()

    html_body = template.format(
        client_name=client["name"],
        month_name=month_name,
        year=year,
        compliance_table=_build_compliance_table(compliances, month_name, year),
    )

    sender_label = account.get("sender_name") or account.get("display_name", "CA Office")
    from_addr    = account["email_address"]
    to_addr      = client["email"]
    subject      = f"Compliance Reminder: {month_name} {year} — Action Required"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = f"{sender_label} <{from_addr}>"
    msg["To"]      = to_addr
    msg.attach(MIMEText(_plain_text(client["name"], compliances, month_name, year), "plain"))
    msg.attach(MIMEText(html_body, "html"))

    return _smtp_send(account, from_addr, to_addr, msg.as_string(), conn)


def test_smtp_connection(account: dict) -> tuple[bool, str]:
    """Verify SMTP credentials without sending a real email."""
    try:
        conn = get_smtp_connection(account, timeout=15)
        conn.quit()
        enc  = _encryption_label(account)
        host = account["smtp_host"]
        port = int(account["smtp_port"])
        return True, (
            f"Connection successful!\n\n"
            f"Server : {host}:{port} ({enc})\n"
            f"Account: {account['username']}"
        )
    except smtplib.SMTPAuthenticationError:
        return False, (
            "Authentication failed.\n\n"
            "Check your email address and App Password.\n"
            "Make sure you are using an App Password, not your regular password."
        )
    except smtplib.SMTPException as exc:
        return False, f"SMTP error: {exc}"
    except OSError as exc:
        return False, f"Network error: {exc}\n\nCheck the SMTP host, port, and encryption settings."


# ── Internal helpers ──────────────────────────────────────────────────────────

def _encryption_label(account: dict) -> str:
    """Return the effective encryption mode as a display string."""
    enc = account.get("encryption")
    if enc in ("STARTTLS", "SSL", "None"):
        return enc
    # backward-compat: old records used use_tls boolean
    return "STARTTLS" if account.get("use_tls", True) else "None"


def get_smtp_connection(account: dict, timeout: int = 20) -> smtplib.SMTP:
    """
    Open an authenticated SMTP connection.

    Handles three encryption modes:
      SSL      — smtplib.SMTP_SSL (port 465 typical)
      STARTTLS — smtplib.SMTP + starttls() (port 587 typical)
      None     — smtplib.SMTP plain (port 25; rarely needed)
    """
    host = account["smtp_host"]
    port = int(account["smtp_port"])
    enc  = _encryption_label(account)

    if enc == "SSL":
        conn = smtplib.SMTP_SSL(host, port, timeout=timeout)
    else:
        conn = smtplib.SMTP(host, port, timeout=timeout)
        conn.ehlo()
        if enc == "STARTTLS":
            conn.starttls()
            conn.ehlo()

    conn.login(account["username"], account["password"])
    return conn


def _smtp_send(
    account: dict,
    from_addr: str,
    to_addr: str,
    raw: str,
    existing_conn: Optional[smtplib.SMTP] = None,
) -> tuple[bool, str]:
    try:
        conn = existing_conn or get_smtp_connection(account, timeout=30)
        conn.sendmail(from_addr, [to_addr], raw)
        if existing_conn is None:
            conn.quit()
        logger.info("Sent reminder → %s", to_addr)
        return True, ""
    except smtplib.SMTPAuthenticationError:
        msg = "SMTP authentication failed — check credentials / App Password."
        logger.error(msg)
        return False, msg
    except smtplib.SMTPRecipientsRefused:
        msg = f"Recipient refused: {to_addr}"
        logger.error(msg)
        return False, msg
    except smtplib.SMTPException as exc:
        logger.error("SMTP error: %s", exc)
        return False, str(exc)
    except OSError as exc:
        logger.error("Network error: %s", exc)
        return False, f"Network error: {exc}"
